version: '3'

services:
  consumer:
    container_name: consumer
    restart: on-failure
    build:
      context: ./app/consumer
      dockerfile: DockerfileConsumer
    depends_on:
    - rabbit

  rabbit:
    container_name: dev_rabbit
    hostname: rabbit
    image: rabbitmq:3.8.9-management
    environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=user
    ports:
    - "5672:5672"
    - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    container_name: db_mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: always
    ports:
    - "5432:3306"
    volumes:
    - db_data:/var/lib/mysql
  app:
    container_name: application
    build:
      context: .
    ports:
      - 8000:5000
    volumes:
      - ./app:/app
    links:
      - db
    depends_on:
      - db
      - rabbit
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
volumes:
  db_data: {}